src/docs/components/announcement-bar.hbs, src/scss/components/_announcement-bar.scss, src/scss/main.scss
looks like the color of the annoucement bar from live is not on the styleguide so I am using primary color
=> create announcement bar

src/docs/components/announcement-bar.hbs, src/js/main.js, src/partials/components/announcement-bar.hbs
just realised the announcement bar on SS is a carousel, here is the update the announcement bar
=> anoouncement bar carousel

src/docs/templates/stockist.hbs, src/js/main.js, src/js/modules/stockist.js, src/partials/sections/instagram.hbs, src/scss/main.scss, src/scss/templates/_stockist.scss
for instagram section, I am using the new one we are using in homepage
=> stockist page

src/partials/compounds/range-intro-apc.hbs
remove class rounded-0 from button to make consistent with another buttons
=> remove class rounded-0

src/js/modules/product-card.js
https://app.clickup.com/t/bfp988
=> add underline to xx review

src/partials/components/announcement-bar.hbs
update font style of annuncement bar
https://app.clickup.com/t/9e04uy?comment=288482904
=> announcement bar font style

src/js/modules/predictive-search.js
no change to JS, only cleaning up errors from ESLint
=> eslint errors cleanup

src/partials/compounds/mega-menu-about.hbs, src/partials/compounds/mega-menu-shop.hbs, src/partials/compounds/mobile-menu.hbs, src/scss/components/_nav.scss, src/scss/sections/_header.scss
https://app.clickup.com/t/9e04uy?comment=181683819
=> header updates

src/scss/sections/_header.scss
fix tooltip position on header scroll up
=> fix tooltip on header scroll up

src/partials/compounds/search-box.hbs, src/scss/core/_type.scss, src/scss/templates/_blog.scss
added a utlility class for link with pink color
=> Link secondary

src/docs/compounds/product-waitlist.hbs, src/docs/templates/product.hbs, src/js/modules/product-template.js, src/partials/components/modal-waitlist.hbs, src/partials/compounds/product-waitlist.hbs, src/scss/components/_modal.scss, src/scss/templates/_collection.scss
https://app.clickup.com/t/f2427v
=> new product waitlist form

src/scss/core/_utilities.scss
=> add media percy to utilities

src/js/modules/predictive-search.js
https://app.clickup.com/t/1d7u39c
add auto focus to the input text search
=> [1d7u39c] auto focus to the input when click search icon

src/partials/components/product-variant-abtest.hbs, src/scss/components/_product-variant-abtest.scss
change store class and add col-2 for image width
=> #1py73vq - Image in variant (PDP)

src/partials/product-image-carousel.hbs, src/scss/components/_product-image-carousel.scss
=> #1vk2rh8 - Add SVG badge on collection page and PDP

src/js/main.js, src/js/modules/dropdown-abtest.js, src/partials/compounds/dropdown-abtest.hbs, src/partials/sections/header.hbs, src/scss/_common.scss, src/scss/components/_dropdown-abtest.scss
=> #1wuy4hu - Account registration in menu bar - desktop

src/scss/sections/_featured-products-abtest.scss
Fixing tab title slightly shifting on tab change
=> 1zfj0hn Redesign Homepage Featured Product and Range page subtitle

src/partials/components/product-variant.hbs, src/scss/components/_product-variant-abtest.scss, src/scss/main.scss, src/scss/product.scss
use these classes to body to activate sections, you can combine the classes
abtest-increase-price-size, abtest-change-price-color, abtest-change-variants-position
also please use eu-store to html
=> 23u5u15 pdp price abtest

package-lock.json, package.json, src/docs/templates/range-aea-abtest.hbs, src/docs/templates/range-apc-abtest.hbs, src/docs/templates/range-tsw-abtest.hbs, src/partials/compounds/product-card-abtest.hbs, src/partials/sections/range-products-abtest.hbs, src/partials/sections/range-result-abtest.hbs, src/scss/range-page-abtest.scss, src/scss/sections/_range-product-abtest.scss, src/scss/sections/_range-result-abtest.scss
update to add badge & carousel
=> #1x0pyz7 - Range page redesign

package-lock.json, package.json, src/docs/components/product-image-carousel-abtest.hbs, src/docs/templates/product-abtest.hbs, src/partials/product-image-carousel-abtest.hbs, src/scss/components/_announcement-bar-abtest.scss, src/scss/components/_product-image-carousel-abtest.scss, src/scss/components/_product-image-carousel.scss, src/scss/main.scss, src/scss/product.scss
https://app.clickup.com/t/2cy2hvx
=> 2cy2hvx - Thumbs carousel under product image

src/partials/sections/featured-products-with-tab.hbs, src/scss/_common.scss, src/scss/components/_buttons-black-abtest.scss
add au-store to html and button-black-abtest-active to body tag to activate the test
=> #2e0gwr7 To change CTA to black colour

src/docs/templates/home.hbs, src/js/main.js, src/js/modules/range-section-abtest.js, src/partials/compounds/product-card.hbs, src/partials/sections/carousel-scroll.hbs, src/partials/sections/featured-products-with-tab.hbs, src/partials/sections/range-abtest.hbs, src/scss/home.scss, src/scss/main.scss, src/scss/sections/_range-section-abtest.scss
@foria 
I added a wrapper div  to **feature product section** to have similar html element with shopidy section, as shopify automaticly added a div wrapper to sections, this section previously don't have wrapper
also added another wrapper to wrap section range tab and featured product, this is for abtest purpose, in this abtest there are 2 variants, one of them need the both section to switch position, so it need a wrapper to wrap both sections, so the position of the two sections can be reverse
=> #296jw8x Range section in homepage

src/partials/compounds/secondary-nav-abtest.hbs, src/partials/sections/header.hbs, src/scss/_common.scss, src/scss/compounds/_secondary-nav-abtest.scss
add uk-store to html tag
add nav__secondary--abtest class to body tag
=> #296c0me - Desktop secondary menu design

src/docs/templates/product.hbs, src/partials/compounds/mobile-menu.hbs, src/partials/compounds/quiz-banner.hbs, src/partials/sections/range-products.hbs
quiz link on PDP & range banner
=> #2f354bu - Skin Quiz + placement on site

src/docs/templates/product.hbs, src/partials/components/product-variant.hbs, src/partials/components/quiz-banner.hbs, src/scss/components/_product-variant-abtest.scss, src/scss/product.scss
add uk-store to html tag
add variant-box--abtest class to body tag
=> #2qg72gm - Variant redesign

src/docs/templates/product.hbs, src/partials/components/modal-variant-subscription.hbs, src/partials/components/product-variant-subscription-v1.hbs, src/partials/components/product-variant-subscription-v2.hbs, src/partials/components/product-variant.hbs, src/scss/components/_product-subscription-abtest.scss, src/scss/components/_product-variant.scss, src/scss/product.scss
add us-store to html tag
add product-subscription--abtest class to body tag
=> 2q4rtc9 Subscription test

src/docs/templates/home.hbs, src/partials/compounds/hero-banner-abtest.hbs, src/partials/sections/hero-carousel-abtest.hbs, src/scss/compounds/_hero-banner-abtest.scss, src/scss/home.scss
add html class : us-store
add class to body : 
variant 1 : hero-banner--abtest-v1
variant 2 : hero-banner--abtest-v2
=> 3gaxmzc new banner design layout

package-lock.json, package.json, src/docs/templates/home.hbs, src/js/modules/featured-products-tab.js, src/partials/compounds/product-card.hbs, src/partials/sections/a-beauty-banner.hbs, src/partials/sections/carousel-scroll.hbs, src/partials/sections/collection-section.hbs, src/partials/sections/hero-ingredients.hbs, src/scss/sections/_collection-section.scss
=> 3nb9adz Homepage updates

src/docs/compounds/product-card-abtest.hbs, src/docs/compounds/product-card.hbs, src/partials/compounds/product-card-abtest.hbs, src/scss/_common.scss, src/scss/compounds/_product-card-abtest.scss, src/scss/core/_utilities.scss
add abtest components product card with price in the cta
=> [3hrx8bc] abtest product card and price in the cta 

src/partials/compounds/product-card-abtest.hbs, src/scss/compounds/_product-card-abtest.scss, src/scss/core/_utilities.scss
add product card abtest button white and hover
=> [3hrx8bc] button white and hover

src/scss/components/_modal.scss
Fixed the by default modal open issue
=> Fixed the by default modal open issue

package-lock.json, package.json, src/partials/compounds/post-card.hbs
- Removed the lazy loading Above the fold images
=> #860pf023n Above the fold Images not lazy-loaded (SS)

src/docs/templates/home.hbs, src/partials/compounds/product-card.hbs, src/scss/_common.scss, src/scss/compounds/_product-card-abtest.scss
add us-store to html tag
add price-cta--abtest-v1 class to body tag
add price-cta--abtest-v2 class to body tag
add price-cta--abtest-v3 class to body tag
add price-cta--abtest-v4 class to body tag
=> #865bk7bfw Price in CTA HP and Collection

package-lock.json, package.json, src/partials/compounds/product-card.hbs, src/scss/compounds/_product-card-abtest.scss
add us-store to html tag
add price-cta--abtest-v1 class to body tag
add price-cta--abtest-v2 class to body tag
add price-cta--abtest-v3 class to body tag
add price-cta--abtest-v4 class to body tag
=> 8669qv48q Price in CTA without decimal & increased text size (HP and Collection)

src/docs/templates/home.hbs, src/scss/_common.scss, src/scss/components/_modal-newsletter-abtest.scss
add class to html : au-store
add class to body : modal-newsletter--abtest
=> 865c8r152 Implement floating button similar to CE

src/docs/templates/collection.hbs, src/partials/compounds/product-card-quiz-abtest.hbs, src/scss/_common.scss, src/scss/compounds/_product-card-quiz-abtest.scss
html : au-store
body class : quiz-banner--abtest
=> 865cgqcz0 Add Skin Quiz to Shop All Collection Page

src/docs/components/modal.hbs, src/partials/components/modal-checkout-upsell.hbs, src/scss/components/_modal.scss
Updates for upsell based on modal consistency updates
=> 865d3n9cf - Upsell Pop Up for Specific Products
